# Generated by Django 4.1 on 2022-08-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_creartablacitas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cita',
            table='citas',
        ),
    ]
