# Generated by Django 4.1 on 2022-08-20 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citas', '0003_agregandoforeignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='especialidadId',
            field=models.ForeignKey(db_column='especialidad_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relacionEspecialidad', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='usuarioId',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='relacionUsuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
