# Generated by Django 4.1 on 2022-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'especialidades',
            },
        ),
    ]
