# Generated by Django 4.1 on 2022-08-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_creacionModeloEspecialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
