# Generated by Django 4.1 on 2022-08-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_creacionModeloEspecialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
