# Generated by Django 4.1 on 2022-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0002_creacionmodelousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.TextField(db_column='contrasena', max_length=50),
        ),
    ]
