# Generated by Django 4.1 on 2022-08-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0004_creacionmodelousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.TextField(db_column='contrasena'),
        ),
    ]
