# Generated by Django 4.1 on 2022-08-19 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_creacionModeloCategorias'),
        ('autorizacion', '0005_creaciontablausuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoriaid',
            field=models.ForeignKey(db_column='categoria_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relacioncategorias', to='categorias.categoria'),
            preserve_default=False,
        ),
    ]
