# Generated by Django 4.1 on 2022-08-19 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_creacionModeloCategorias'),
        ('autorizacion', '0009_relacioncategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoriaid',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='relacioncategorias', to='categorias.categoria'),
        ),
    ]
