# Generated by Django 4.1 on 2022-08-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipousuario', models.CharField(choices=[('cliente', 'cliente'), ('doctor', 'doctor')], db_column='tipo_usuario', default='cliente', max_length=10)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
